### ISSUE TITLE
Is it "include" or "includes"?

### ISSUE THREAD

**Issue by adamdicarlo0** [jetpack-io/devbox-plugins#2]
The README instructions say "the include section" and then show a JSON sample that uses the key `includes`.

> To use a plugin, add the following reference to the include section of your devbox.json file.

```json
"includes": [
    "github:jetpack-io/devbox-plugins?dir=<plugin-name>"
],
```

**Comment by Lagoja** [comment]
Updated. Also working on cleaning up the official docs. Thanks for reporting this!
